version: '3'
services:
    server:
        container_name: 'docker-node-mongo'
        restart: always
        build: .
        ports:
            - '3030:3030'
        links:
            - mongo
    mongo:
        container_name: 'mongo'
        volumes:
            - dbdata:/data/db
        image: mongo
        ports: 
            - '27017:27017'
volumes:
    dbdata: